project:
  type: website
  preview:
    port: 4200
    browser: true
  output-dir: /html_doc_si_web

website:
  title: "Doc SI de l'OEIL"
  navbar:
    left:
      - text: "Accueil"
        href: index.qmd
  sidebar:
    style: "docked"
    search: true
    contents: auto
    collapse-below : sm
    collapse-level : 1

bibliography: references.bib
comments:
  hypothesis: false
format:
  html:
    theme: cosmo
    code-copy: true
  docx:
    reference-doc: custom-reference.docx
    toc: true
    toc-depth: 2
    number-sections: true
    highlight-style: github
  pdf: 
    toc: true
    number-sections: true
    highlight-style: github
    code-block-theme: github
    code-block-font-size: 10
    code-block-line-numbers: true
    code-block-wrap: true
    code-block-margin: 0.5
    code-block-padding: 0.5
    code-block-border-radius: 0.5
    code-block-background-color: "#f8f9fa"
    code-block-border-color: "#f8f9fa"
    code-block-border-width: 0.5
    code-block-border-style: solid
    code-block-shadow: true
    code-block-shadow-color: "#f8f9fa"
    code-block-shadow-x: 0.5
    code-block-shadow-y: 0.5
    code-block-shadow-blur: 0.5
    code-block-shadow-spread: 0.5
    code-block-shadow-opacity: 0.5
    code-block-shadow-inset: false
    code-block-shadow-direction: out
    code-block-shadow-vertical: true
    code-block-shadow-horizontal: true

date: today
last-modified: today
lang: fr
date-format: long
author: Hugo Roussaffa
execute:
  cache: true