# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  branches:
    include:
    - main

jobs:
  - job: prod
    displayName: "Déploiement sur le serveur de PROD"
    pool:
      name: Isengard
    steps:
    - checkout: self
    - script: |
        cp -R $(Build.SourcesDirectory)/* /website_doc_si      
    #- script: docker compose up -d --build --force-recreate doc_si_web
