---
title: COPIL FIN de production 2024-02-27 
last-modified: 2024-02-26 21:31:20Z
date: 2024-02-26 21:13:02Z
latitude: -22.25582340
longitude: 166.45052430
altitude: 0.0000
---

2024-02-27

Reste :

\- Documentation

| ID  | Title | Iteration Path | State | Effort | Tags | temps passé | Assigned To | Remaining Work |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| [568](https://dev.azure.com/Oeilnc/EO4DM/_workitems/edit/568) | Documenter la mise en production | EO4DM\\release 1\\Sprint 2 Réalisation | Doing | 1   | Phase 1 |     | m.neuhauser |     |

|     |     |     |     |     |     |     |     |     |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| [778](https://dev.azure.com/Oeilnc/EO4DM/_workitems/edit/778) | faire la doc de configuration des commandes des données ASCAT livrées sur FTP | EO4DM\\release 1\\Sprint 2 Réalisation | To Do |     | Phase 1 |     | m.neuhauser | 2   |

Chaines :

| ID  | Title | Iteration Path | State | Effort | Tags | temps passé | Assigned To | Remaining Work |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| [732](https://dev.azure.com/Oeilnc/EO4DM/_workitems/edit/732) | Déploiement de la chaine prévisionnelle de sécheresse | EO4DM\\release 1\\Sprint 2 Réalisation | To Do | 8   | Phase 1 |     | m.neuhauser |     |

Monitoring

| ID  | Title | Iteration Path | State | Effort | Tags | temps passé | Assigned To | Remaining Work |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| [751](https://dev.azure.com/Oeilnc/EO4DM/_workitems/edit/751) | Envoyer un email pour chaque lancement de chaine et intégrer dedans si le traitement à réussi ou s'il a échoué | EO4DM\\release 1.2 | To Do | 5   | Phase 3 |     | m.neuhauser |     |