---
title: 'Restitution 1 pollux : point d''avancement'
last-modified: 2022-09-15 23:34:49Z
date: 2022-09-15 22:03:52Z
---

16 Septembre 2022
9h00

Parties prenante :
francois lebrogne PSUD
christina organisation de protection de la nature IUCN : UE / best
Astronomie Association
SCO (ornitologie) : programme SOS petrele, échouage
Mairie Mont dore : préservation biodiversitié, gestion éclairage publique
Mairie Paita
 Endemia, animation de la liste rouge locale  UICN 
Gestion des aires protégées PSUD
Ville de nouméa 
Ville de Dumbéa
Point focal Best


Présentation par Adrien B.

synthèse : principalement échouage oiseau marin
Année atypique en terme d'échouage + 300 , principalement Nea
habitualement env 100 oiseau 
pas de facteur d'explication à ce stade
source :VIIRS 2014-2021 (correction depuis 2014)
luminance diffusion dans l'atmosphère
Jillin: seul capteur de nuit
in situ Ninox : calibration

Bureau étude DSL telescope : ils representent 90% des études réalisées en France

Méthodologie de croisement, simple avec différents enjeux.

kiam: compléter la donnée sur les tortues ?
Accompagnement sur l'interprétation des observations, demande ciblé pour un atelier (ACE, Aménagement des provinces, Synergie). Une des limites et necessité de reactivé cette approche.

croisement de la bd espèce de la PSUD.

Contribution publique/privée
 

ENdemia : filtrer les lezard

suivi dans le temps des indicateurs

donnée de base : est on sur de ne pas introduire une 

province sud : quelles reserves pour mettre en labelisation ciel étoilée (stage fin d'année/début d'année 6 mois). encore mal defini. 
Syndicat intercommunale de Foa/saramea/farino (parc des grandes fougères).

Projet CNES et Arianne Espace (projet sur le même site) + acteur educatif (?)

question UE :
reproduction de la methodologie ailleurs ? métropole ?
risque de la non intégration dans les politique publique .

scientifique : peut explorer, étude compliquée vaste

"heritage du projet"

pratique des miniers : zone d'extraction. dynamique à la croissance.

perspective : mesure de population d'insecte, par ecoute sonore. étude de correlation temporelle et spatiale.
cibler par type d'espèce. 

impact sur les roussettes (point de nidification). Malik fabrice brecha. aucune litterature scientifique. Pas un problème en zone ubaine. association de pression de chasse.

lifou : annulation des mariages / Covid 
déplacement de la population. délocalisation sur KoweKara des mariages.

usage dans le schema directeur d'eclairage publique.



