---
title: replant
last-modified: 2024-03-14 04:46:48Z
date: 2024-03-14 03:17:19Z
---

Plusieurs projets de reboisement.
lien avec le projet PEBACC+

PROE/SPREP 
CPS mais biodiv et rechaufement climatique basé à Fidji

Lancement COPIL lancement oct 2023 -> 2025 démontrateur terrain/ enjeux protection trait de cote grace aux mangroves
pnord lute espece envahissante maitrise des feux
pil : trait de cote

intégration des SFN dans les politique d'adaptation au changement climatique.
analyse des resilliances  pendant 1 an (evoque l'oeil pour la qualité des bases de données) : 15M
cherche x10

lien pas clair entre les 2
notion de cout efficacités, clarté à apporté + suivi long terme
soutient au initiative de suivi

projet de restauration : pb incendie et herbivorie




Séléction 6/42

20 pages + 2 pages annexes (cartes, listes...). 
en français
on reprend le chemin initiale 
c'est l'AFD qui décide.
date début à partir d'octobre 2024, voir fin  d'année 2024

proposé un titre + Replant'NC
cocher les ecosystème cible : foret foret seche, mangrove...
pas d'obligation d'etre porté sur l'espèce envahissante
adatation changement climatique 
répondre aux autres défis societaux

beneficiaire du projet ?  total de la population. scanné de très près. calcul cout/pers

justification, on va peut etre se repéter. il faut le faire

but: etre ambitieux. ce à quoi tend ce projet : contribu à la restauration des ecosytèmes forestier.
faire reference à des rapport stratégique rapport du GIEC, étude scientifique  et bibliographique. comment s'incrit dans la dynamique du territoire et dans la région. 5 POINTS (?) 
objectifs des ODD.

démontrer les bénéfices pour la biodiversité. 5 point si on prouve qu'on est un SFN.

indiquer qui sont les parties prenante et détaillé leur role, leur contribution attendu.


Montrer comment on renforce les capacités et partenariat locaux. comment on implique les agents de la structure. chiffre : nombre Homme/Femme

Durabilité (nottament à partir des capacité renforcé).

messages clés dans la communication et visibilité. faire le plan de com dès la proposition. 

saisonalité pour le reboisement .

Calendrier par livrable. source de verification de notre activité (ex. un rapport, compte rendu) tout ce qui prouve au bailleur que les choses sont faites.
conditionne le paiement des subventions

analyse des risques. en mettre minimum 4 ! probailité d'occurence / incidence / mesures d'attenuation (adhésion à l'outil)

le plus de lettre de soutien possible (gouv, province, commune)


budget : bien vue si co-financement mais pas dans le détaillé
dans détaillé mettre uniquement ce que paie KIWA.

on peut augmenter mais en justifiant l'augmentation en cohérence avec les actions. on ne pas passé à une autre catégorie 

commentaire, enlever les frais de gestion. mais lourd. couvert par les cout indirect
salaire pas plus 30% mais accepté au cas pas cas.  
rapportage tout les 6 mois, frais de personnel.

facture et preuve de paiement

détail par personne, ils regardent plutôt le montant total

lie cadre logique avec le budget
prévoir 10% de tresorerie pour le versement dela derniere tranche.
important de valoriser insertion sociale (jeune et femme). expert spécifique sur les risques environnement et sociaux.

submit  : mettre en copie UICN (chloé)
- cv des principaux memebre de la structure (cadres).
- evaluation des risque financier de la structure

feuille de temps / facture / preuve de paiement/
fiche de temps par heure / pê par jour
taux journalier variable dans les periodes.

petite marge de manoeuvre avec accord 
tout achat, il faut demander une validation AFD. 4 semaines de delais.
