---
title: 'Troubleshooting :  bilbo package gee'
last-modified: 2024-07-02 22:52:25Z
date: 2023-04-14 01:44:17Z
latitude: -22.25582340
longitude: 166.45052430
altitude: 0.0000
---

`ConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))`

`ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))` 



`'SSLError(MaxRetryError("HTTPSConnectionPool(host=\'earthengine.googleapis.com\', port=443): Max retries exceeded with url: /$discovery/rest?version=v1alpha&prettyPrint=false (Caused by SSLError(SSLZeroReturnError(6, \'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)\')))"))'`

`SSLError(MaxRetryError("HTTPSConnectionPool(host='earthengine.googleapis.com', port=443): Max retries exceeded with url: /v1alpha/projects/earthengine-legacy/value:compute?prettyPrint=false&alt=json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))"))`


`SSLError(MaxRetryError("HTTPSConnectionPool(host='earthengine.googleapis.com', port=443): Max retries exceeded with url: /v1alpha/projects/earthengine-legacy/algorithms?prettyPrint=false&alt=json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))")) `

`SSLError(MaxRetryError("HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))"))`

`EEException('The caller does not have permission')`


```
RefreshError('invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.'})
```