---
title: JupyterHub
last-modified: 2022-06-21 02:48:43Z
date: 2021-06-29 04:18:46Z
latitude: -22.27430000
longitude: 166.44680000
altitude: 0.0000
---

 Les installations des libs principales se font avec le user root dans le docker

`docker pull jupyterhub/jupyterhub`
`pip install jupyterlab`


Installation de plusieurs version de python [doc](https://levelup.gitconnected.com/install-multiple-python-versions-on-linux-8bd6d301d78c)



installer nodejs
```
curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt update
sudo apt-get install -y nodejs
```
accéder

## Utiliser plusieurs versions de python et y accéder par jupyter
Utiliser pyenv pour simplifier les installation des environnements virtuels

Editer .profile
```
# Pyenv environment variables
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
```

Editer .bashrc
```
# Pyenv initialization
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```

Installation de pyenv
```
sudo apt-get update --yes
sudo apt-get install --yes libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libgdbm-dev lzma lzma-dev tcl-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev wget curl make build-essential python-openssl
```

Installation de python 3.6.13  dans un répertoire commun à tous les utilisateurs

```
$(pyenv which python-build) -v 3.6.13 /usr/local/
```


Depuis la session d'un utilisateur
- créer un environnement virtuel sur la base d'un python disponible. par ex 3.6

```
virtualenv -p /usr/bin/python3.6 virtualenv/venv36
```

- activer l'environnement
- télécharger les librairies suivantes :
```
python -m pip install --upgrade pip
python -m pip install ipykernel
```



installer le nouveau kernel jupyter

```
venv36/bin/python -m ipykernel install --user --name "quickda" --display-name "quickda"
```

se deconnecter de jupyter hub

# Maintenance 

Entrer dans le container 
```
sudo apt-get update
sudo apt-list --upgradable
sudo apt-get upgrade
```

